Update migrate-repo-gitlab2ghec

diff --git a/migration-scripts/migrate-repo-gitlab2ghec b/migration-scripts/migrate-repo-gitlab2ghec
--- a/migration-scripts/migrate-repo-gitlab2ghec
+++ b/migration-scripts/migrate-repo-gitlab2ghec
@@ -35,21 +35,21 @@ configure_source_and_destination() {
     export GL_PAT="$6"
     export GHEC_DEST_ORG_NAME="$7"
     export GHEC_MAIN_BRANCH="$8"
-    echo "Source: https://$GTLab_SOURCE_USER_NAME@gitlab.com/$GTLab_SOURCE_ORG_NAME/$REPO_NAME.git"
-    echo "Destination: https://$GHEC_USER_NAME@github.com/$GHEC_DEST_ORG_NAME/$REPO_NAME.git"
+    echo "Source: https://$GL_SOURCE_USER_NAME@gitlab.com/$GL_SOURCE_ORG_NAME/$GL_REPO_NAME.git"
+    echo "Destination: https://$GHEC_USER_NAME@github.com/$GHEC_DEST_ORG_NAME/$GL_REPO_NAME.git"
 }
 
 clone_from_gitlab() {
 
     # Use http for EF instead of https
-    SOURCE_REPO_URL="https://gitlab.gh-services-partners.com/$GTLab_SOURCE_ORG_NAME/$REPO_NAME.git"
+    SOURCE_REPO_URL="https://gitlab.gh-services-partners.com/$GL_SOURCE_ORG_NAME/$GL_REPO_NAME.git"
     git clone --mirror "$SOURCE_REPO_URL"
     clone_status=$?
     if [ $clone_status -ne 0 ]; then
         echo "ERROR: Failed to clone repo $SOURCE_REPO_URL"
         exit 1
     fi
-    cd "$REPO_NAME".git || {
+    cd "$GL_REPO_NAME".git || {
         echo "ERROR: Unable to cd into the repo"
         exit 1
     }
@@ -58,7 +58,7 @@ clone_from_gitlab() {
 delete_existing_ghec_repo_targetOrg() {
     # Delete existing repo in Github Enterprise Cloud
     if [ "$GHEC_DELETE_REPO_BEFORE_CREATE" == "true" ]; then
-        gh repo delete "$GHEC_DEST_ORG_NAME"/"$REPO_NAME" --yes || true
+        gh repo delete "$GHEC_DEST_ORG_NAME"/"$GL_REPO_NAME" --yes || true
     fi
 }
 
@@ -66,18 +66,18 @@ push_to_dest_ghec() {
 
     #delete_existing_ghec_repo_targetOrg
 
-    DESTINATION_REPO_URL="https://$GHEC_USER_NAME:$GHEC_USER_PAT@github.com/$GHEC_DEST_ORG_NAME/$REPO_NAME.git"
+    DESTINATION_REPO_URL="https://$GHEC_USER_NAME:$GHEC_USER_PAT@github.com/$GHEC_DEST_ORG_NAME/$GL_REPO_NAME.git"
 
     #create repo in GHEC
-    #gh repo create "$GHEC_DEST_ORG_NAME"/"$REPO_NAME" --internal
+    #gh repo create "$GHEC_DEST_ORG_NAME"/"$GL_REPO_NAME" --internal
 
     # Use Curl if you don't have gh cli installed
     API_URL="https://api.github.com/orgs/$GHEC_DEST_ORG_NAME/repos"
     echo "API_URL: $API_URL"
 
-    curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GHEC_USER_PAT" -H "X-GitHub-Api-Version: 2022-11-28" $API_URL -d '{"name":"'"$REPO_NAME"'"}'
+    curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GHEC_USER_PAT" -H "X-GitHub-Api-Version: 2022-11-28" $API_URL -d '{"name":"'"$GL_REPO_NAME"'"}'
 
-    # curl -H "Authorization: Bearer $GHEC_USER_PAT" $API_URL -d '{"name":"'"$REPO_NAME"'"}'
+    # curl -H "Authorization: Bearer $GHEC_USER_PAT" $API_URL -d '{"name":"'"$GL_REPO_NAME"'"}'
 
     create_status=$?
     if [ $create_status -ne 0 ]; then
@@ -86,18 +86,18 @@ push_to_dest_ghec() {
     fi
     git remote set-url origin "$DESTINATION_REPO_URL"
     git push
-    GHEC_DEST_COMMITS_COUNT=$(curl -s -H "Authorization: Bearer $GHEC_USER_PAT" -X HEAD -I "https://api.github.com/repos/$GHEC_DEST_ORG_NAME/$REPO_NAME/commits?per_page=1" | grep -i "link:" | awk '{print $4}' | sed 's/.*page=\([0-9]*\)>;.*/\1/')
+    GHEC_DEST_COMMITS_COUNT=$(curl -s -H "Authorization: Bearer $GHEC_USER_PAT" -X HEAD -I "https://api.github.com/repos/$GHEC_DEST_ORG_NAME/$GL_REPO_NAME/commits?per_page=1" | grep -i "link:" | awk '{print $4}' | sed 's/.*page=\([0-9]*\)>;.*/\1/')
     GitLab_SOURCE_COMMITS_COUNT=$(curl -s --header "PRIVATE-TOKEN: YOUR_PRIVATE_TOKEN" "https://your-gitlab-url/api/v4/projects/PROJECT_ID/repository/commits?per_page=1" | jq '. | length')
-    GHEC_DEST_BRANCH_COUNT=$(curl -s -H "Authorization: Bearer $GHEC_USER_PAT" "https://api.github.com/repos/$GHEC_DEST_ORG_NAME/$REPO_NAME/branches" | jq '. | length')
+    GHEC_DEST_BRANCH_COUNT=$(curl -s -H "Authorization: Bearer $GHEC_USER_PAT" "https://api.github.com/repos/$GHEC_DEST_ORG_NAME/$GL_REPO_NAME/branches" | jq '. | length')
     GitLab_SOURCE_BRANCH_COUNT=$(curl -s --header "Private-Token: Your-Private-Token" "https://your-gitlab-url/api/v4/projects/:id/repository/branches" | jq 'length')
 
     if [ $GHEC_DEST_COMMITS_COUNT -ne 0 ]; then
         if [ $GHEC_DEST_COMMITS_COUNT -ne $GHEC_SOURCE_COMMITS_COUNT ]; then
-            echo "ERROR: Commits not matched $REPO_NAME"
+            echo "ERROR: Commits not matched $GL_REPO_NAME"
             exit 1
         fi
         if [ $GHEC_DEST_BRANCH_COUNT -ne $GHEC_SOURCE_BRANCH_COUNT ]; then
-            echo "ERROR: Branches count not matched $REPO_NAME"
+            echo "ERROR: Branches count not matched $GL_REPO_NAME"
             exit 1
         fi
     else
@@ -116,7 +116,7 @@ configure_source_and_destination $*
 
 # Remove the local directory of the repository if it exists from a previous run. 
 # This is to ensure that the script starts with a clean state.
-rm -rf "$REPO_NAME".git
+rm -rf "$GL_REPO_NAME".git
 
 # Call the clone_from_source_ghec function to clone the repository from the source GitLab instance. 
 # It clones a bare repository (including all branches and tags) and then navigates into the cloned repository directory.
@@ -132,7 +132,7 @@ push_to_dest_ghec
 REPO_SIZE=$(du -sh | awk '{print $1}')
 
 # Remove the local repository directory after the migration is done.
-rm -rf "$REPO_NAME".git
+rm -rf "$GL_REPO_NAME".git
 
 # Capture the end time of the script.
 END_TIME=$(date +%s)
@@ -150,5 +150,5 @@ touch "$MIGRATION_LOG_FILE_NAME"
 
 # Log the name of the repository, its size, and the duration of the migration process to both the console and the log file. 
 # The tee -a command is used to append the output to the log file.
-echo "$REPO_NAME Size:$REPO_SIZE Duration:$((END_TIME - START_TIME))" | tee -a "$MIGRATION_LOG_FILE_NAME"
+echo "$GL_REPO_NAME Size:$REPO_SIZE Duration:$((END_TIME - START_TIME))" | tee -a "$MIGRATION_LOG_FILE_NAME"
 
